### ISSUE TITLE
Пара мелочей

### ISSUE THREAD

**Issue by avasyukov** [IvanLudvig/Matrix3D#1]
// По сути всё нормально, поэтому мне лень создавать отдельный тикет на каждую мелочь

1. Пофиксить логический порядок операндов вот здесь:
https://github.com/IvanLudvig/Matrix3D/blob/7b94813571b4f1177cc1fc4231ce08f45e32fe0d/Vector3D.cpp#L66-L68
А то сейчас получается:
```
A = (1, 2, 3)
B = (1, 1, 1)
A - B = (0, -1, -2)
```

2. Предполагалось, что произведение двух векторов - скалярное, а не покоординатное.

3. Я бы всё-таки "внешние" операторы перенёс из main в Vector3D и Matrix3D - не критично, но логически они как будто части тех компонентов.

**Comment by IvanLudvig** [comment]
Все исправлено

**Comment by avasyukov** [comment]
Ок, согласен
